//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ultrasonic.DownloadManager.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDownloadDataProviderService")]
    public interface IDownloadDataProviderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadDataProviderService/GetCategories", ReplyAction="http://tempuri.org/IDownloadDataProviderService/GetCategoriesResponse")]
        string GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadDataProviderService/GetInformation", ReplyAction="http://tempuri.org/IDownloadDataProviderService/GetInformationResponse")]
        string GetInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadDataProviderService/GetDownloadInformation", ReplyAction="http://tempuri.org/IDownloadDataProviderService/GetDownloadInformationResponse")]
        string GetDownloadInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadDataProviderService/GetFileList", ReplyAction="http://tempuri.org/IDownloadDataProviderService/GetFileListResponse")]
        string GetFileList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDownloadDataProviderServiceChannel : Ultrasonic.DownloadManager.ServiceReference1.IDownloadDataProviderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DownloadDataProviderServiceClient : System.ServiceModel.ClientBase<Ultrasonic.DownloadManager.ServiceReference1.IDownloadDataProviderService>, Ultrasonic.DownloadManager.ServiceReference1.IDownloadDataProviderService {
        
        public DownloadDataProviderServiceClient() {
        }
        
        public DownloadDataProviderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DownloadDataProviderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownloadDataProviderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownloadDataProviderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public string GetInformation() {
            return base.Channel.GetInformation();
        }
        
        public string GetDownloadInformation() {
            return base.Channel.GetDownloadInformation();
        }
        
        public string GetFileList() {
            return base.Channel.GetFileList();
        }
    }
}
